Improve environment variable expansion

diff --git a/s3-sync-entrypoint b/s3-sync-entrypoint
--- a/s3-sync-entrypoint
+++ b/s3-sync-entrypoint
@@ -43,7 +43,7 @@
 #   <command>           A command and arguments for it
 
 
-set -euo pipefail
+set -eo pipefail
 
 if [[ ${#} -ge 1 ]]; then
   for a in "${@}"; do
@@ -51,10 +51,14 @@ if [[ ${#} -ge 1 ]]; then
   done
 fi
 
+[[ -n "${INPUT_DATA_DIR}" ]] || INPUT_DATA_DIR="${PWD}"
+[[ -n "${OUTPUT_DATA_DIR}" ]] || OUTPUT_DATA_DIR="${PWD}"
+
+set -u
+
 SCRIPT_PATH=$(realpath "${0}")
 SCRIPT_NAME=$(basename "${SCRIPT_PATH}")
 SCRIPT_VERSION='v0.1.2'
-
 DRYRUN=0
 SKIP_OUTPUT_ON_ERROR=0
 SYNC_COMMAND='sync'
@@ -91,7 +95,21 @@ function abort {
   exit 1
 }
 
+function read_str {
+  if [[ ${SUPPRESS_EXPANSION} -eq 0 ]]; then
+    bash -c "eval 'echo ${*}'"
+  else
+    echo "${*}"
+  fi
+}
+
 function validate_s3_uri {
+  for s in "${@}"; do
+    [[ "${s}" =~ ^s3://.+ ]] || abort "invalid URI: ${s}"
+  done
+}
+
+function validate_s3_object {
   for s in "${@}"; do
     aws s3 ls "${s}" > /dev/null
   done
@@ -109,14 +127,6 @@ function echo_n_log {
     echo "${*}" | tee -a "${OUTPUT_LOG_FILE}"
   else
     echo "${*}"
-  fi
-}
-
-function read_str {
-  if [[ ${SUPPRESS_EXPANSION} -eq 0 ]]; then
-    eval "echo -n ${*}"
-  else
-    echo -n "${*}"
   fi
 }
 
@@ -212,7 +222,7 @@ if [[ ${#INPUT_S3_URIS[@]} -gt 0 ]]; then
     INBOUND_SYNC="${SYNC_COMMAND}"
   fi
   echo_n_log "INBOUND_SYNC:         ${INBOUND_SYNC}"
-  validate_s3_uri "${INPUT_S3_URIS[@]}"
+  validate_s3_object "${INPUT_S3_URIS[@]}"
 fi
 
 if [[ -n "${OUTPUT_S3_URI}" ]]; then
@@ -225,6 +235,10 @@ if [[ -n "${OUTPUT_S3_URI}" ]]; then
   fi
   echo_n_log "OUTBOUND_SYNC:        ${OUTBOUND_SYNC}"
   validate_s3_uri "${OUTPUT_S3_URI}"
+fi
+
+if [[ -n "${OUTPUT_LOG_S3_URI}" ]]; then
+  validate_s3_uri "${OUTPUT_LOG_S3_URI}"
 fi
 
 if [[ ${#COMMAND[@]} -gt 0 ]]; then
@@ -254,6 +268,7 @@ if [[ -n "${OUTPUT_S3_URI}" ]]; then
     echo 'The outbound sync was skipped due to the exit code.'
   else
     echo_n_eval "aws s3 ${OUTBOUND_SYNC} ${OUTPUT_DATA_DIR} ${OUTPUT_S3_URI}"
+    validate_s3_uri "${OUTPUT_S3_URI}"
   fi
 fi
 
@@ -264,6 +279,7 @@ echo_n_log "TOTAL_ELAPSED_TIME:   $(date --date=@${ELAPSED_SECONDS} -u +%H:%M:%S
 if [[ -n "${OUTPUT_LOG_S3_URI}" ]]; then
   if [[ ${SKIP_OUTPUT_ON_ERROR} -eq 0 ]] || [[ ${COMMAND_EXIT_CODE} -eq 0 ]]; then
     echo_n_eval "aws s3 cp ${OUTPUT_LOG_FILE} ${OUTPUT_LOG_S3_URI}"
+    validate_s3_uri "${OUTPUT_LOG_S3_URI}"
   fi
 fi
 
